-- This file is generated by build.sh
local V = {}

------ packer/opt ------

V.Comment_nvim                 = '40f5587'
V.LuaSnip                      = '8ecf139'
V.base46                       = '2e925ef'
V.better_escape_nvim           = 'd5ee0ce'
V.bufferline_nvim              = '374ef05'
V.cmp_buffer                   = '12463cf'
V.cmp_nvim_lsp                 = 'e6b5feb'
V.cmp_nvim_lua                 = 'd276254'
V.cmp_path                     = '466b6b8'
V.cmp_luasnip                  = 'a9de941'
V.feline_nvim                  = '528d6ec'
V.friendly_snippets            = '0677f70'
V.gitsigns_nvim                = 'ffd06e3'
V.indent_blankline_nvim        = '8567ac8'
V.lsp_signature_nvim           = '2496aac'
V.nvim_autopairs               = 'aea9131'
V.nvim_cmp                     = 'cd694b8'
V.nvim_colorizer_lua           = '6c8b149'
V.nvim_lsp_installer           = '0b27bf1'
V.nvim_lspconfig               = '0f06f7b'
V.nvim_tree_lua                = '9d26594'
V.nvim_treesitter              = 'c9ebd16'
V.nvim_web_devicons            = 'cde67b5'
V.packer_nvim                  = '4dedd3b'
V.telescope_nvim               = '01fc5a9'
V.vim_matchup                  = '485e711'

------ packer/start ------

V.extensions                   = '54d3d62'
V.impatient_nvim               = '2337df7'
V.nvterm                       = '4efafd5'
V.plenary_nvim                 = 'bbd13b1'

return V
