-- This file is generated by build.sh
local V = {}

------ packer/opt ------

V.Comment_nvim                 = 'master'
V.LuaSnip                      = 'master'
V.base46                       = 'master'
V.better_escape_nvim           = 'master'
V.bufferline_nvim              = 'main'
V.cmp_buffer                   = 'main'
V.cmp_nvim_lsp                 = 'main'
V.cmp_nvim_lua                 = 'main'
V.cmp_path                     = 'main'
V.cmp_luasnip                  = 'master'
V.feline_nvim                  = 'master'
V.friendly_snippets            = 'main'
V.gitsigns_nvim                = 'main'
V.indent_blankline_nvim        = 'master'
V.lsp_signature_nvim           = 'master'
V.nvim_autopairs               = 'master'
V.nvim_cmp                     = 'main'
V.nvim_colorizer_lua           = 'master'
V.nvim_lsp_installer           = 'main'
V.nvim_lspconfig               = 'master'
V.nvim_tree_lua                = 'master'
V.nvim_treesitter              = 'master'
V.nvim_web_devicons            = 'master'
V.packer_nvim                  = 'master'
V.telescope_nvim               = 'master'
V.vim_matchup                  = 'master'
V.which_key_nvim               = 'main'

------ packer/start ------

V.extensions                   = 'main'
V.impatient_nvim               = 'main'
V.nvterm                       = 'main'
V.plenary_nvim                 = 'master'

return V
